import React from "react";
import MainFooter from "../../Components/Footers/MainFooter";
import AuthHeader from "../../Components/Headers/AuthHeader";

import Img1 from '../../Assets/img/become_a_vendor.jpg';
import Img2 from '../../Assets/img/become_a_affiliate.jpg';
import Img3 from '../../Assets/img/buyer.jpg';

import '../../Assets/css/otherPages.css';
import { Link } from "react-router-dom";

function index() {
	return (
		<>
			<AuthHeader />
			<div className="page__hero get__started">
				<div className="section__container">
					<div className="page__head--text">
						<h3 className="page--title">Get started</h3>
						<p className="head--text">
							Clubmerce affiliate marketing platform, where we dive into the exciting
							world of passive income how to leverage it through affiliate marketing.
							Whether you're a beginner seeking to start your online business or an
							experienced marketer looking to expand your revenue streams.
						</p>
						<span className="get-started-actions">
							<Link className="content__button" to="/affiliate-resourses">
								Get Started As an Affiliate
							</Link>
							<Link	 className="content__button" to="/vendor-resourses">
								Get Started As a Vendor
							</Link>
						</span>
					</div>
				</div>
			</div>

			<main>
				<section className="page__section">
					<div className="section__container">
						<h3 className="section__title">What is Affiliate Marketing?</h3>
						<p className="section__text">
							In this section, we'll provide a clear definition of affiliate
							marketing. We'll explain how it works, highlighting the roles of
							Affiliates, Product Vendors, and consumers in the process. We'll also
							discuss the concept of affiliate commissions and how they're earned
							through referrals and conversions.
						</p>
						<p className="section__description">
							Affiliate marketing is a dynamic and mutually beneficial business model
							that connects product vendors and affiliate promoters, allowing them to
							collaborate and generate revenue together. It has gained significant
							popularity in the digital age due to its effectiveness and potential for
							generating passive income. At its core, affiliate marketing involves
							three key players: the product vendor, the affiliate promoter, and the
							consumer. Let's delve deeper into how this system works and the
							advantages it brings to both vendors and promoters.
						</p>
						<div className="get__started--content">
							<div className="content">
								<img
									className="content__image"
									src={Img1}
									alt={Img1}
								/>
								<div className="content__description">
									<h4 className="content__title">
										Understanding the Role of the Product Vendor:
									</h4>
									<p className="section__description">
										A product vendor can be an individual entrepreneur or a
										company that creates and sells products or services. Their
										primary goal is to expand their reach and increase sales.
										However, marketing products and reaching potential customers
										can be a challenging task. This is where affiliate marketing
										steps in.
									</p>
									<p className="section__description">
										By enlisting affiliate promoters, vendors can tap into their
										network, expertise, and marketing channels to reach a wider
										audience. They provide the promoters with a unique referral
										link or an affiliate code, which tracks the traffic and
										sales generated by the promoters.
									</p>
								</div>
							</div>
						</div>

						<span>
							<h3 className="content__title">Benefits for Product Vendors </h3>
							<div className="content__cards">
								<div className="content__card">
									<i className="fa-solid fa-chart-line icon get-started-icon"></i>
									<h4 className="card__title">Increased Reach</h4>
									<p className="card__description">
										Affiliate marketing enables vendors to expand their reach
										exponentially by leveraging the network and marketing
										efforts of multiple promoters.
									</p>
								</div>
								<div className="content__card">
									<i className="fa-solid fa-house-circle-check icon get-started-icon"></i>
									<h4 className="card__title">Cost-Effective Marketing:</h4>
									<p className="card__description">
										Traditional advertising methods can be expensive and
										uncertain in terms of ROI. Vendors only pay commissions when
										a conversion occurs.
									</p>
								</div>
								<div className="content__card">
									<i className="fa-solid fa-chart-bar icon get-started-icon"></i>
									<h4 className="card__title">Performance-Based Model</h4>
									<p className="card__description">
										Affiliate marketing is a performance-based model, meaning
										vendors only pay promoters when they deliver results.
									</p>
								</div>
							</div>
						</span>

						<div className="content">
							<div className="content__description">
								<h4 className="content__title">The Role of the Affiliate Promoter:</h4>
								<p className="section__description">
									Affiliate promoters are individuals or organizations that have
									an online presence, such as bloggers, influencers, website
									owners, or social media personalities. They have built a
									following and earned the trust of their audience. Promoters
									leverage their credibility and influence to recommend products
									or services to their followers.
								</p>
								<p className="section__description">
									When an affiliate promoter joins an affiliate program, they
									receive a unique referral link or code associated with the
									vendor's product. They strategically promote this link through
									various marketing channels, including blog posts, social media
									platforms, email campaigns, and more. The referral link allows
									the vendor to track the traffic and conversions generated by the
									promoter accurately.
								</p>
							</div>
							<img
								className="content__image"
								src={Img2}
								alt={Img2}
							/>
						</div>

						<span>
							<h3 className="content__title">Benefits for Affiliate Promoters:</h3>
							<div className="content__cards">
								<div className="content__card">
									<i className="fa-solid fa-money-bill-trend-up icon get-started-icon"></i>
									<h4 className="card__title">Passive Income</h4>
									<p className="card__description">
										Affiliate marketing offers promoters the opportunity to earn
										passive income.
									</p>
								</div>
								<div className="content__card">
									<i className="fa-solid fa-meno icon get-started-icon"></i>
									<h4 className="card__title">Diverse Product Selection</h4>
									<p className="card__description">
										Affiliate promoters can choose from a wide range of products
										and services to promote.
									</p>
								</div>
								<div className="content__card">
									<i className="fa-solid fa-meno icon get-started-icon"></i>
									<h4 className="card__title">Minimal Investment</h4>
									<p className="card__description">
										Affiliate marketing requires minimal upfront investment from
										promoters.
									</p>
								</div>
								<div className="content__card">
									<i className="fa-solid fa-meno icon get-started-icon"></i>
									<h4 className="card__title">Skill Development & Networking</h4>
									<p className="card__description">
										Affiliate marketing provides promoters with an opportunity
										to develop various skills such as content creation, digital
										marketing, analytics, and audience engagement.
									</p>
								</div>
								<div className="content__card">
									<i className="fa-solid fa-meno icon get-started-icon"></i>
									<h4 className="card__title">Performance-Based Earnings</h4>
									<p className="card__description">
										Affiliate promoters have the potential to earn substantial
										commissions based on their performance, As they hone their
										marketing skills, build a loyal audience.
									</p>
								</div>
							</div>
						</span>

						<div className="content">
							<img className="content__image" src={Img3} alt={Img3} />
							<div className="content__description">
								<h4 className="content__title">The Consumer's Role:</h4>
								<p className="section__description">
									AThe consumer, or the target audience, is a vital part of the
									affiliate marketing ecosystem. When they click on an affiliate
									promoter's referral link and make a purchase, they are referred
									to as a conversion or a sale. The consumer does not pay anything
									extra by using the affiliate link; instead, the vendor shares a
									portion of the revenue earned with the promoter.
								</p>
								<p className="section__description">
									Now that we understand the roles of the key players, let's
									explore the benefits of affiliate marketing for both vendors and
									promoters:
								</p>
							</div>
						</div>

						<span>
							<p className="section__description">
								Overall, affiliate marketing benefits both product vendors and
								affiliate promoters by creating a mutually beneficial ecosystem.
								Vendors gain increased brand exposure, expanded reach, and
								cost-effective marketing, while promoters can earn passive income,
								leverage diverse product selections, and develop valuable skills.
								The success of affiliate marketing lies in fostering strong
								relationships between vendors and promoters, built on trust,
								transparency, and effective collaboration.
							</p>
							<span className="get-started-actions">
								<Link className="content__button" to="/vendor-resourses">
									Get Started As a Vendor
								</Link>
								<Link className="content__button" to="/affiliate-resourses">
									Get Started As an Affiliate
								</Link>
							</span>
						</span>
					</div>
				</section>
			</main>

            <MainFooter />
		</>
	);
}

export default index;
